<Project>
  <PropertyGroup>
    <LangVersion>Latest</LangVersion>
    <Copyright>Ilya Belyanskiy 2020</Copyright>
    <Authors>Belyanskiy Ilya</Authors>
    <PackageProjectUrl>https://laraue.com/blog/projects/ef-core-triggers</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Laraue/Laraue.EfCoreTriggers</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <!-- Designate all projects as non-package projects by default -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>